language: java

addons:
  sonarcloud:
    organization: "elijanajonuzi"
    token:
      secure: "ca11effa27483bbdbc902b7f3e6c903b10fb8065" # encrypted value of your token

script:
  - ./gradlew sonarqube
  
  notifications:
  slack: noseryoungpro-fpp6320:F8Zk99pqamIEpDZgY4CTQ2rH
   on_success: always
   on_failure: always
   